# Generated by Django 3.2.7 on 2022-02-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220202_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
    ]
