# Generated by Django 3.2.7 on 2022-02-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_boards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='boards',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
