# Generated by Django 3.2.7 on 2022-02-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_uploaded',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_name',
        ),
    ]
